### ISSUE TITLE
People have issues with this package

### ISSUE THREAD

**Issue by aminya** [JuliaComputing/JuliaAcademyData.jl#2]
Wouldn't it better to teach the students learn how to load the data themselves instead of using a ready package?

Some issues that people face for running this:
https://github.com/JuliaComputing/JuliaAcademyMaterials/issues/19

**Comment by yuxi-liu-wired** [comment]
I just downloaded the repo, put it in a convenient place, 

then replaced the first cell in the notebooks with 

```julia
datapath(x::AbstractString, coursename="Deep learning with Flux") = "C:\\Users\\Yuxi\\Desktop\\Programming\\julia-Foundations of Machine Learning\\JuliaAcademyData.jl\\courses\\$coursename\\$x"
```

**Comment by logankilpatrick** [comment]
Hey @aminya @yuxiliu1995 I would appreciate it if you could try this again. I think I resolved some of the errors you all were having.
